CREATE TABLE IF NOT EXISTS SyncSession (
    id TEXT NOT NULL PRIMARY KEY,
    type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    step TEXT NOT NULL DEFAULT '',
    progress INTEGER NOT NULL DEFAULT 0,
    logs TEXT NOT NULL DEFAULT '[]',
    startedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completedAt DATETIME,
    updatedAt DATETIME NOT NULL
);

ALTER TABLE SyncSession ADD COLUMN metadata TEXT NOT NULL DEFAULT '{}';
