INSERT OR IGNORE INTO "CompanyMembershipType" ("name", "createdAt") VALUES
  ('Accelerator Shared Workspace', CURRENT_TIMESTAMP),
  ('Active EIR Workbook User', CURRENT_TIMESTAMP),
  ('Associate Membership - Corporate', CURRENT_TIMESTAMP),
  ('Associate Membership - Startup/SME', CURRENT_TIMESTAMP),
  ('Associate Membership (10,000+)', CURRENT_TIMESTAMP),
  ('Associate Membership (12-50)', CURRENT_TIMESTAMP),
  ('Associate Membership (50 - 500)', CURRENT_TIMESTAMP),
  ('Associate Membership (500 - 10,000)', CURRENT_TIMESTAMP),
  ('Associate Membership (Complimentary)', CURRENT_TIMESTAMP),
  ('Associate Membership (Sponsorship)', CURRENT_TIMESTAMP),
  ('Associate Membership (University)', CURRENT_TIMESTAMP),
  ('Co-Working Student Rate', CURRENT_TIMESTAMP),
  ('Convertible Garage - Large', CURRENT_TIMESTAMP),
  ('Convertible Garage - Small', CURRENT_TIMESTAMP),
  ('Curriculum Instructor', CURRENT_TIMESTAMP),
  ('Enterprise Membership', CURRENT_TIMESTAMP),
  ('Equity & Innovation Scholarship', CURRENT_TIMESTAMP),
  ('Fabrication Customer', CURRENT_TIMESTAMP),
  ('Garage - Large', CURRENT_TIMESTAMP),
  ('Garage - Medium', CURRENT_TIMESTAMP),
  ('Garage - Small', CURRENT_TIMESTAMP),
  ('Hardtech Development Consultants/Contractors', CURRENT_TIMESTAMP),
  ('Landis Family Fellowship', CURRENT_TIMESTAMP),
  ('Membership - AI - C Cohort 1', CURRENT_TIMESTAMP),
  ('Membership - AI - IIOT Cohort 1', CURRENT_TIMESTAMP),
  ('Membership - AI - MedTech Cohort 1', CURRENT_TIMESTAMP),
  ('Membership - AI - MedTech Cohort 2', CURRENT_TIMESTAMP),
  ('Mentee Program', CURRENT_TIMESTAMP),
  ('Mentorship Program', CURRENT_TIMESTAMP),
  ('mHUB Board of Directors', CURRENT_TIMESTAMP),
  ('mHUB Community', CURRENT_TIMESTAMP),
  ('mHUB Executive Committee', CURRENT_TIMESTAMP),
  ('mHUB Staff', CURRENT_TIMESTAMP),
  ('mHUB Venture Board', CURRENT_TIMESTAMP),
  ('mPOWER Program', CURRENT_TIMESTAMP),
  ('mPOWER Program Cohort 2', CURRENT_TIMESTAMP),
  ('Office - Large', CURRENT_TIMESTAMP),
  ('Office - Medium', CURRENT_TIMESTAMP),
  ('Office - Partner', CURRENT_TIMESTAMP),
  ('Office - Small', CURRENT_TIMESTAMP),
  ('Partner Office - Large', CURRENT_TIMESTAMP),
  ('Partner Office - Medium', CURRENT_TIMESTAMP),
  ('Partner Office - Small', CURRENT_TIMESTAMP),
  ('Punch Card Membership', CURRENT_TIMESTAMP),
  ('Punch Card Test', CURRENT_TIMESTAMP),
  ('PunchCard', CURRENT_TIMESTAMP),
  ('Reserved Desk', CURRENT_TIMESTAMP),
  ('Shared Workspace', CURRENT_TIMESTAMP),
  ('Shared Workspace – Intern', CURRENT_TIMESTAMP),
  ('Shop - Full-Time', CURRENT_TIMESTAMP),
  ('Shop - Part-Time', CURRENT_TIMESTAMP),
  ('Social Membership', CURRENT_TIMESTAMP),
  ('Storage - Large Shelf', CURRENT_TIMESTAMP),
  ('Wet Lab', CURRENT_TIMESTAMP),
  ('x- Associate Membership - IIT', CURRENT_TIMESTAMP),
  ('x- Associate Membership - Marmon', CURRENT_TIMESTAMP),
  ('x- Associate Membership - Northwestern', CURRENT_TIMESTAMP),
  ('x- Associate Membership - UChicago Argonne', CURRENT_TIMESTAMP),
  ('x- Associate Membership - University of Illinois', CURRENT_TIMESTAMP),
  ('xs- Lathe Advanced User', CURRENT_TIMESTAMP),
  ('xs- Lathe Production', CURRENT_TIMESTAMP),
  ('xs- Tormach CNC Mill III (super user)', CURRENT_TIMESTAMP),
  ('xs- Tormach CNC Mill Production', CURRENT_TIMESTAMP);
