CREATE TABLE IF NOT EXISTS "PortalAccessType" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO "PortalAccessType" ("name", "createdAt") VALUES
  ('Associate Membership - Corporate', CURRENT_TIMESTAMP),
  ('Associate Membership - Startup/SME', CURRENT_TIMESTAMP),
  ('Associate Membership (10,000+)', CURRENT_TIMESTAMP),
  ('Associate Membership (12-50)', CURRENT_TIMESTAMP),
  ('Associate Membership (50 - 500)', CURRENT_TIMESTAMP),
  ('Associate Membership (500 - 10,000)', CURRENT_TIMESTAMP),
  ('Associate Membership (Complimentary)', CURRENT_TIMESTAMP),
  ('Associate Membership (Sponsorship)', CURRENT_TIMESTAMP),
  ('Associate Membership (University)', CURRENT_TIMESTAMP),
  ('Co-Working Student Rate', CURRENT_TIMESTAMP),
  ('Convertible Garage - Large', CURRENT_TIMESTAMP),
  ('Convertible Garage - Small', CURRENT_TIMESTAMP),
  ('Enterprise Membership', CURRENT_TIMESTAMP),
  ('Fabrication Customer', CURRENT_TIMESTAMP),
  ('Garage - Large', CURRENT_TIMESTAMP),
  ('Garage - Medium', CURRENT_TIMESTAMP),
  ('Garage - Small', CURRENT_TIMESTAMP),
  ('Hardtech Development Consultants/Contractors', CURRENT_TIMESTAMP),
  ('Membership - AI - C Cohort 1', CURRENT_TIMESTAMP),
  ('Membership - AI - IIOT Cohort 1', CURRENT_TIMESTAMP),
  ('Membership - AI - MedTech Cohort 1', CURRENT_TIMESTAMP),
  ('Membership - AI - MedTech Cohort 2', CURRENT_TIMESTAMP),
  ('mHUB Board of Directors', CURRENT_TIMESTAMP),
  ('mHUB Executive Committee', CURRENT_TIMESTAMP),
  ('mHUB Staff', CURRENT_TIMESTAMP),
  ('mHUB Venture Board', CURRENT_TIMESTAMP),
  ('Office - Large', CURRENT_TIMESTAMP),
  ('Office - Medium', CURRENT_TIMESTAMP),
  ('Office - Partner', CURRENT_TIMESTAMP),
  ('Office - Small', CURRENT_TIMESTAMP),
  ('Partner Office - Large', CURRENT_TIMESTAMP),
  ('Partner Office - Medium', CURRENT_TIMESTAMP),
  ('Partner Office - Small', CURRENT_TIMESTAMP),
  ('Punch Card Membership', CURRENT_TIMESTAMP),
  ('Reserved Desk', CURRENT_TIMESTAMP),
  ('Shared Workspace', CURRENT_TIMESTAMP),
  ('Shared Workspace – Intern', CURRENT_TIMESTAMP),
  ('Social Membership', CURRENT_TIMESTAMP),
  ('Wet Lab', CURRENT_TIMESTAMP);
